version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: DBname
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
  # Redis instance
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  db_data:
